name: Debian Release Build

on:
  push:
    tags:
      - 'v*' # 当推送格式为 v* 的标签时触发，如 v1.0.0
  workflow_dispatch: # 允许手动触发

jobs:
  build-debian:
    name: Build for Debian 12 x86_64
    runs-on: ubuntu-latest
    container:
      image: debian:12
    
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential pkg-config libssl-dev git

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      
      - name: Build with features
        run: |
          cargo build --release --features hickory-dns,aead-cipher-2022,dns-over-https
      
      - name: Package
        run: |
          mkdir -p release
          cd target/release
          tar -czvf ../../release/shadowsocks-rust-debian12-x86_64.tar.gz sslocal ssserver ssurl ssmanager
          cd ../..
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/shadowsocks-rust-debian12-x86_64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
